name: CI

on: ["push", "pull_request"]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v1.2.2

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm i

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run coverage:all
        env:
          SQUARE_BASE_URL: ${{ secrets.SQUARE_BASE_URL }}
          SQUARE_SANDBOX_BASE_URL: ${{ secrets.SQUARE_SANDBOX_BASE_URL }}
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.node-version, '12.')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
