name: CI

on: [ "push", "pull_request" ]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v2

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Lint code
        run: npm run lint

      - name: Check publish sdk
        run: npm run publish:dev:dry

      - name: Type check
        run: npm run typecheck

      - name: Run tests and covarage
        run: npm run coverage:ci
        env:
          SQUARE_BASE_URL: ${{ secrets.SQUARE_BASE_URL }}
          SQUARE_SANDBOX_BASE_URL: ${{ secrets.SQUARE_SANDBOX_BASE_URL }}
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.node-version, '14.')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
